export default Object.freeze({
  REGISTER_USER: 'REGISTER_USER',
  REGISTER_USER_STARTED: 'REGISTER_USER_STARTED',
  REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',
  REGISTER_USER_FAILURE: 'REGISTER_USER_FAILURE',
  LOGIN_USER: 'LOGIN_USER',
  LOGIN_USER_STARTED: 'LOGIN_USER_STARTED',
  LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
  LOGIN_USER_FAILURE: 'LOGIN_USER_FAILURE'
});
